name:                neurocar
version:             0.1.0.0
github:              "cornelius-sevald/neurocar"
license:             BSD3
author:              "Cornelius Sevald-Krause"
maintainer:          "cornelius.sevald@gmail.com"
copyright:           "2020 Cornelius Sevald-Krause"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/cornelius-sevald/neurocar#readme>

dependencies:
- base >= 4.7 && < 5
- random >= 1.1
- extra >= 1.6.18
- tuple >= 0.3.0.2
- text >= 1.2.3.1
- split >= 0.2.3.3
- linear >= 1.20
- vector >= 0.12.0.2
- hmatrix >= 0.20.0.0
- mtl >= 2.2.2
- transformers >= 0.5.6.2
- monad-loops >= 0.4.3
- normaldistribution >= 1.1.0.3
- errors >= 2.3.0
- sdl2 >= 2.5.0.0
- sdl2-ttf >= 2.1.0
- lens >= 4.0

library:
  source-dirs: src

executables:
  neurocar-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - neurocar

tests:
  neurocar-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - neurocar
